version: '3.8'

services:
  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/html/data
    restart: always
